# Generated by Django 4.0.3 on 2022-04-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('key_word', models.TextField()),
                ('word1', models.TextField()),
                ('word2', models.TextField()),
                ('word3', models.TextField()),
                ('word4', models.TextField()),
                ('word5', models.TextField()),
            ],
        ),
    ]
