# Generated by Django 4.0.3 on 2022-04-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_key_remove_data_key_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='UserData',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
