# Generated by Django 4.0.3 on 2022-04-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_product_userdata_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('keyboard', models.TextField()),
            ],
        ),
    ]
