# Generated by Django 4.0.3 on 2022-04-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userhistory_wordlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
